using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace Covide.Web
{
    public class ColorCode
    {
        public int Id { get; set; }
        public string HexTriplet { get; set; }
        public string Name { get; set; }
    }

    public class CovideDataContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=Data.db");
        }

        public DbSet<ColorCode> ColorCodes { get; set; }
    }

    public static class CovideDataSeeder
    {
        

        public static void Seed(IServiceProvider provider)
        {
            var db = provider.GetRequiredService<CovideDataContext>();

            db.Database.EnsureCreated();

            if (!db.ColorCodes.Any())
            {
                db.ColorCodes.Add(new ColorCode { HexTriplet = "000000", Name = "Black" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "0C090A", Name = "Night" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2C3539", Name = "Gunmetal" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2B1B17", Name = "Midnight" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "34282C", Name = "Charcoal" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "25383C", Name = "Dark Slate Grey" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3B3131", Name = "Oil" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "413839", Name = "Black Cat" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3D3C3A", Name = "Iridium" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "463E3F", Name = "Black Eel" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4C4646", Name = "Black Cow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "504A4B", Name = "Gray Wolf" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "565051", Name = "Vampire Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5C5858", Name = "Gray Dolphin" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "625D5D", Name = "Carbon Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "666362", Name = "Ash Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6D6968", Name = "Cloudy Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "726E6D", Name = "Smokey Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "736F6E", Name = "Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "837E7C", Name = "Granite" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "848482", Name = "Battleship Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B6B6B4", Name = "Gray Cloud" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "D1D0CE", Name = "Gray Goose" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E5E4E2", Name = "Platinum" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "BCC6CC", Name = "Metallic Silver" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "98AFC7", Name = "Blue Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6D7B8D", Name = "Light Slate Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "657383", Name = "Slate Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "616D7E", Name = "Jet Gray" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "646D7E", Name = "Mist Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "566D7E", Name = "Marble Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "737CA1", Name = "Slate Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4863A0", Name = "Steel Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2B547E", Name = "Blue Jay" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2B3856", Name = "Dark Slate Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "151B54", Name = "Midnight Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "000080", Name = "Navy Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "342D7E", Name = "Blue Whale" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "15317E", Name = "Lapis Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "151B8D", Name = "Denim Dark Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "0000A0", Name = "Earth Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "0020C2", Name = "Cobalt Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "0041C2", Name = "Blueberry Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2554C7", Name = "Sapphire Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "1569C7", Name = "Blue Eyes" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2B60DE", Name = "Royal Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "1F45FC", Name = "Blue Orchid" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6960EC", Name = "Blue Lotus" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "736AFF", Name = "Light Slate Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "357EC7", Name = "Windows Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "368BC1", Name = "Glacial Blue Ice" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "488AC7", Name = "Silk Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3090C7", Name = "Blue Ivy" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "659EC7", Name = "Blue Koi" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "87AFC7", Name = "Columbia Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "95B9C7", Name = "Baby Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "728FCE", Name = "Light Steel Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "2B65EC", Name = "Ocean Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "306EFF", Name = "Blue Ribbon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "157DEC", Name = "Blue Dress" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "1589FF", Name = "Dodger Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6495ED", Name = "Cornflower Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6698FF", Name = "Sky Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "38ACEC", Name = "Butterfly Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "56A5EC", Name = "Iceberg" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5CB3FF", Name = "Crystal Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3BB9FF", Name = "Deep Sky Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "79BAEC", Name = "Denim Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "82CAFA", Name = "Light Sky Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "82CAFF", Name = "Day Sky Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "A0CFEC", Name = "Jeans Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B7CEEC", Name = "Blue Angel" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B4CFEC", Name = "Pastel Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C2DFFF", Name = "Sea Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C6DEFF", Name = "Powder Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "AFDCEC", Name = "Coral Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "ADDFFF", Name = "Light Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "BDEDFF", Name = "Robin Egg Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CFECEC", Name = "Pale Blue Lily" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E0FFFF", Name = "Light Cyan" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EBF4FA", Name = "Water" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F0F8FF", Name = "AliceBlue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F0FFFF", Name = "Azure" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CCFFFF", Name = "Light Slate" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "93FFE8", Name = "Light Aquamarine" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9AFEFF", Name = "Electric Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7FFFD4", Name = "Aquamarine" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "00FFFF", Name = "Cyan or Aqua" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7DFDFE", Name = "Tron Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "57FEFF", Name = "Blue Zircon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8EEBEC", Name = "Blue Lagoon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "50EBEC", Name = "Celeste" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4EE2EC", Name = "Blue Diamond" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "81D8D0", Name = "Tiffany Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "92C7C7", Name = "Cyan Opaque" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "77BFC7", Name = "Blue Hosta" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "78C7C7", Name = "Northern Lights Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "48CCCD", Name = "Medium Turquoise" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "43C6DB", Name = "Turquoise" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "46C7C7", Name = "Jellyfish" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7BCCB5", Name = "Blue green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "43BFC7", Name = "Macaw Blue Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3EA99F", Name = "Light Sea Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3B9C9C", Name = "Dark Turquoise" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "438D80", Name = "Sea Turtle Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "348781", Name = "Medium Aquamarine" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "307D7E", Name = "Greenish Blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5E7D7E", Name = "Grayish Turquoise" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4C787E", Name = "Beetle Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "008080", Name = "Teal" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4E8975", Name = "Sea Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "78866B", Name = "Camouflage Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "848b79", Name = "Sage Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "617C58", Name = "Hazel Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "728C00", Name = "Venom Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "667C26", Name = "Fern Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "254117", Name = "Dark Forest Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "306754", Name = "Medium Sea Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "347235", Name = "Medium Forest Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "437C17", Name = "Seaweed Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "387C44", Name = "Pine Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "347C2C", Name = "Jungle Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "347C17", Name = "Shamrock Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "348017", Name = "Medium Spring Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4E9258", Name = "Forest Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6AA121", Name = "Green Onion" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4AA02C", Name = "Spring Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "41A317", Name = "Lime Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "3EA055", Name = "Clover Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6CBB3C", Name = "Green Snake" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6CC417", Name = "Alien Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4CC417", Name = "Green Apple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "52D017", Name = "Yellow Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4CC552", Name = "Kelly Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "54C571", Name = "Zombie Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "99C68E", Name = "Frog Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "89C35C", Name = "Green Peas" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "85BB65", Name = "Dollar Bill Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8BB381", Name = "Dark Sea Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9CB071", Name = "Iguana Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B2C248", Name = "Avocado Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9DC209", Name = "Pistachio Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "A1C935", Name = "Salad Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7FE817", Name = "Hummingbird Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "59E817", Name = "Nebula Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "57E964", Name = "Stoplight Go Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "64E986", Name = "Algae Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5EFB6E", Name = "Jade Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "00FF00", Name = "Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5FFB17", Name = "Emerald Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "87F717", Name = "Lawn Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8AFB17", Name = "Chartreuse" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6AFB92", Name = "Dragon Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "98FF98", Name = "Mint green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B5EAAA", Name = "Green Thumb" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C3FDB8", Name = "Light Jade" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CCFB5D", Name = "Tea Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B1FB17", Name = "Green Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "BCE954", Name = "Slime Green" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EDDA74", Name = "Goldenrod" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EDE275", Name = "Harvest Gold" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFE87C", Name = "Sun Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFFF00", Name = "Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFF380", Name = "Corn Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFFFC2", Name = "Parchment" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFFFCC", Name = "Cream" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFF8C6", Name = "Lemon Chiffon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFF8DC", Name = "Cornsilk" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F5F5DC", Name = "Beige" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FBF6D9", Name = "Blonde" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FAEBD7", Name = "AntiqueWhite" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F7E7CE", Name = "Champagne" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFEBCD", Name = "BlanchedAlmond" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F3E5AB", Name = "Vanilla" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "ECE5B6", Name = "Tan Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFE5B4", Name = "Peach" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFDB58", Name = "Mustard" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFD801", Name = "Rubber Ducky Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FDD017", Name = "Bright Gold" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EAC117", Name = "Golden brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F2BB66", Name = "Macaroni and Cheese" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FBB917", Name = "Saffron" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FBB117", Name = "Beer" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFA62F", Name = "Cantaloupe" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E9AB17", Name = "Bee Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E2A76F", Name = "Brown Sugar" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "DEB887", Name = "BurlyWood" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFCBA4", Name = "Deep Peach" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C9BE62", Name = "Ginger Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E8A317", Name = "School Bus Yellow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EE9A4D", Name = "Sandy Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C8B560", Name = "Fall Leaf Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "D4A017", Name = "Orange Gold" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C2B280", Name = "Sand" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C7A317", Name = "Cookie Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C68E17", Name = "Caramel" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B5A642", Name = "Brass" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "ADA96E", Name = "Khaki" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C19A6B", Name = "Camel brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CD7F32", Name = "Bronze" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C88141", Name = "Tiger Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C58917", Name = "Cinnamon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "AF9B60", Name = "Bullet Shell" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "AF7817", Name = "Dark Goldenrod" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B87333", Name = "Copper" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "966F33", Name = "Wood" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "806517", Name = "Oak Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "827839", Name = "Moccasin" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "827B60", Name = "Army Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "786D5F", Name = "Sandstone" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "493D26", Name = "Mocha" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "483C32", Name = "Taupe" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6F4E37", Name = "Coffee" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "835C3B", Name = "Brown Bear" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F5217", Name = "Red Dirt" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F462C", Name = "Sepia" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C47451", Name = "Orange Salmon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C36241", Name = "Rust" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C35817", Name = "Red Fox" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C85A17", Name = "Chocolate" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CC6600", Name = "Sedona" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E56717", Name = "Papaya Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E66C2C", Name = "Halloween Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F87217", Name = "Pumpkin Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F87431", Name = "Construction Cone Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E67451", Name = "Sunrise Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FF8040", Name = "Mango Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F88017", Name = "Dark Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FF7F50", Name = "Coral" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F88158", Name = "Basket Ball Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F9966B", Name = "Light Salmon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E78A61", Name = "Tangerine" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E18B6B", Name = "Dark Salmon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E77471", Name = "Light Coral" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F75D59", Name = "Bean Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E55451", Name = "Valentine Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E55B3C", Name = "Shocking Orange" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FF0000", Name = "Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FF2400", Name = "Scarlet" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F62217", Name = "Ruby Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F70D1A", Name = "Ferrari Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F62817", Name = "Fire Engine Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E42217", Name = "Lava Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E41B17", Name = "Love Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "DC381F", Name = "Grapefruit" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C34A2C", Name = "Chestnut Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C24641", Name = "Cherry Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C04000", Name = "Mahogany" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C11B17", Name = "Chilli Pepper" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9F000F", Name = "Cranberry" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "990012", Name = "Red Wine" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8C001A", Name = "Burgundy" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "954535", Name = "Chestnut" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7E3517", Name = "Blood Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8A4117", Name = "Sienna" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7E3817", Name = "Sangria" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "800517", Name = "Firebrick" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "810541", Name = "Maroon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7D0541", Name = "Plum Pie" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7E354D", Name = "Velvet Maroon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7D0552", Name = "Plum Velvet" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F4E52", Name = "Rosy Finch" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F5A58", Name = "Puce" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F525D", Name = "Dull Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B38481", Name = "Rosy Brown" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C5908E", Name = "Khaki Rose" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C48189", Name = "Pink Bow" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C48793", Name = "Lipstick Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E8ADAA", Name = "Rose" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "ECC5C0", Name = "Rose Gold" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EDC9AF", Name = "Desert Sand" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FDD7E4", Name = "Pig Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FCDFFF", Name = "Cotton Candy" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFDFDD", Name = "Pink Bubble Gum" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FBBBB9", Name = "Misty Rose" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FAAFBE", Name = "Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FAAFBA", Name = "Light Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F9A7B0", Name = "Flamingo Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E7A1B0", Name = "Pink Rose" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E799A3", Name = "Pink Daisy" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E38AAE", Name = "Cadillac Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F778A1", Name = "Carnation Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E56E94", Name = "Blush Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F660AB", Name = "Hot Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FC6C85", Name = "Watermelon Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F6358A", Name = "Violet Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F52887", Name = "Deep Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E45E9D", Name = "Pink Cupcake" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E4287C", Name = "Pink Lemonade" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F535AA", Name = "Neon Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FF00FF", Name = "Magenta" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E3319D", Name = "Dimorphotheca Magenta" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F433FF", Name = "Bright Neon Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "D16587", Name = "Pale Violet Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C25A7C", Name = "Tulip Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "CA226B", Name = "Medium Violet Red" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C12869", Name = "Rogue Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C12267", Name = "Burnt Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C25283", Name = "Bashful Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C12283", Name = "Dark Carnation Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B93B8F", Name = "Plum" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7E587E", Name = "Viola Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "571B7E", Name = "Purple Iris" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "583759", Name = "Plum Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4B0082", Name = "Indigo" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "461B7E", Name = "Purple Monster" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "4E387E", Name = "Purple Haze" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "614051", Name = "Eggplant" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "5E5A80", Name = "Grape" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6A287E", Name = "Purple Jam" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7D1B7E", Name = "Dark Orchid" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "A74AC7", Name = "Purple Flower" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B048B5", Name = "Medium Orchid" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "6C2DC7", Name = "Purple Amethyst" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "842DCE", Name = "Dark Violet" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8D38C9", Name = "Violet" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7A5DC7", Name = "Purple Sage Bush" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "7F38EC", Name = "Lovely Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8E35EF", Name = "Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "893BFF", Name = "Aztech Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "8467D7", Name = "Medium Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "A23BEC", Name = "Jasmine Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "B041FF", Name = "Purple Daffodil" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C45AEC", Name = "Tyrian Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9172EC", Name = "Crocus Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "9E7BFF", Name = "Purple Mimosa" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "D462FF", Name = "Heliotrope Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E238EC", Name = "Crimson" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C38EC7", Name = "Purple Dragon" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C8A2C8", Name = "Lilac" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E6A9EC", Name = "Blush Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E0B0FF", Name = "Mauve" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "C6AEC7", Name = "Wisteria Purple" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "F9B7FF", Name = "Blossom Pink" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "D2B9D3", Name = "Thistle" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E9CFEC", Name = "Periwinkle" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "EBDDE2", Name = "Lavender Pinocchio" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "E3E4FA", Name = "Lavender blue" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FDEEF4", Name = "Pearl" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFF5EE", Name = "SeaShell" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FEFCFF", Name = "Milk White" });
                db.ColorCodes.Add(new ColorCode { HexTriplet = "FFFFFF", Name = "White" });

                db.SaveChanges();
            }
        }
    }
}
